//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class myCHDEntities1 : DbContext
{
    public myCHDEntities1()
        : base("name=myCHDEntities1")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Application> Applications { get; set; }
    public virtual DbSet<Forum> Fora { get; set; }
    public virtual DbSet<ForumReply> ForumReplies { get; set; }
    public virtual DbSet<Membership> Memberships { get; set; }
    public virtual DbSet<OfferTorrent> OfferTorrents { get; set; }
    public virtual DbSet<Profile> Profiles { get; set; }
    public virtual DbSet<Role> Roles { get; set; }
    public virtual DbSet<Torrent> Torrents { get; set; }
    public virtual DbSet<TorrentComment> TorrentComments { get; set; }
    public virtual DbSet<Ttype> Ttypes { get; set; }
    public virtual DbSet<User> Users { get; set; }
    public virtual DbSet<ViewForum> ViewForums { get; set; }
}
